version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/client/app/node_modules
      - .:/usr/client/app